apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
  labels:
    app: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 850924742604.dkr.ecr.us-east-2.amazonaws.com/mydockerrepo:build-${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   # ✅ matches Dockerfile (EXPOSE 8080)
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-app
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - name: http
      port: 80          # ✅ external-facing port (browser uses this)
      targetPort: 8080  # ✅ forwards to container's 8080
      protocol: TCP


